# Generated by Django 6.0.3 on 2026-04-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urls',
            name='used_count',
            field=models.IntegerField(default=0),
        ),
    ]
