# Generated by Django 6.0.3 on 2026-04-07 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_urls_used_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urls',
            name='user',
        ),
        migrations.AddField(
            model_name='urls',
            name='user_username',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.DeleteModel(
            name='users',
        ),
    ]
