# Generated by Django 6.0.3 on 2026-04-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_urls_user_urls_user_username_delete_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='user_username',
            field=models.CharField(default='zhassyn', max_length=150),
            preserve_default=False,
        ),
    ]
